### ISSUE TITLE
Template spec

### ISSUE THREAD

**Issue by LHerskind** [AztecProtocol/aztec-connect-bridges#113]
There should be a template of a spec, that has sections for some stuff we expect all bridges to elaborate on. But also with sections on how certain properties are ensured and edge-cases are handled, as it can be used as the first line of defence to figure out if the bridge implementation has its bases covered.

**Comment by critesjosh** [comment]
adding a link to our google doc for reference https://docs.google.com/document/d/18sDT8CaoLwmmPiuQhi2UKKOvHtjW8SHvYwvTUbdEdMc/edit
