### ISSUE TITLE
DAI Shield Fails

### ISSUE THREAD

**Issue by empm0ney** [AztecProtocol/aztec-connect-bridges#302]
DAI shielding is not working…

https://github.com/AztecProtocol/aztec-connect/issues/21#issue-1511105868

**Comment by cheethas** [comment]
Thank you for reporting this, the issue appears to have been resolved upstream. So I will close here also. Feel free to reopen the [upstream issue](https://github.com/AztecProtocol/aztec-connect/issues/21#issue-1511105868) if anything changes!
